name: Laravel CI/CD

on:
  push:
    branches:
      - main

env:
  BUILD_NUMBER: ${{ github.run_number }}
  IMAGE_NAME: laravel:${{ github.run_number }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy files to remote server
        run: |
          rsync -avz --exclude=".git" ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USERNAME }}/laravel

      - name: Install Docker on server (if not present)
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            if ! command -v docker &> /dev/null; then
              sudo apt update
              sudo apt install -y docker.io
              sudo usermod -aG docker $USER
              newgrp docker
            fi
          EOF

      - name: Build Docker image on server
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
            cd ~/laravel
            docker build -t $IMAGE_NAME .
          EOF

      - name: Run Laravel container (optional or as update)
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
            docker rm -f laravel-container || true
            docker run -d --name laravel-container -p 80:8000 -v ~/laravel:/var/www/html $IMAGE_NAME
          EOF
